# Generated by Django 3.0 on 2019-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryContent',
            fields=[
                ('day', models.TextField(default='2019-12-01')),
                ('date', models.FloatField()),
                ('object_text', models.TextField(default='')),
                ('raw_text', models.TextField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default='')),
                ('user_name', models.TextField(default='叶子逸')),
                ('user_img', models.TextField(default='http://127.0.0.1:8000/image/user_img_generic.jpeg')),
                ('digest', models.TextField(default='')),
                ('date', models.FloatField()),
                ('emotion', models.TextField(default='00000000')),
                ('score', models.FloatField(default=0)),
                ('day', models.TextField(default='2019-12-01')),
                ('diary_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TodoData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('expired', models.IntegerField()),
                ('finished', models.IntegerField(default=0)),
                ('date', models.FloatField()),
                ('day', models.TextField(default='2019-12-01')),
            ],
        ),
    ]
