# Generated by Django 3.0 on 2019-12-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tododata',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tododata',
            name='expired',
        ),
    ]
