# Generated by Django 3.0 on 2019-12-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20191211_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='user_name',
            field=models.TextField(default='人小智'),
        ),
    ]
